support subdir for run-all, kill-all, status

diff --git a/sm b/sm
--- a/sm
+++ b/sm
@@ -2,10 +2,9 @@
 # version 1.0  License: GPL 2.0
 # author: chenwumail@gmail.com 2018
 
-if [ "x${SM_DIR}" == "x" ]; then
+if [ "x${SM_DIR}" = "x" ]; then
   SM_DIR=${HOME}/sm #default svc dir is /home/{work}/sm
 fi
-
 
 read_ini () {
   file=$1;section=$2;item=$3;
@@ -42,9 +41,15 @@ usage() {
 ############### svc main ##################
 sm_cmd=$1
 sm_name=$2
-if [ "x${sm_cmd}" == "x" ]; then
+if [ "x${sm_cmd}" = "x" ]; then
   usage
   exit 1
+fi
+
+sm_dir=""
+sm_short_name=${sm_name#*/}
+if [ ! $sm_name = $sm_short_name ]; then
+  sm_dir=${sm_name%/*}
 fi
 
 ECHO="echo -e"
@@ -52,6 +57,8 @@ os=`uname`
 if [ "${os}" = "Darwin" ]; then
   ECHO="echo"
 fi
+
+IGNORE_SUBDIR="nosub"
 
 case $sm_cmd in
   # one initilize command, careful for SM_DIR, default is ${HOME}/app
@@ -86,19 +93,24 @@ case $sm_cmd in
     ;;
   # one exec command, foregroud execute service in user directory
   exec)
-    if [ "x${sm_name}" == "x" ]; then
+    if [ "x${sm_name}" = "x" ]; then
       usage
       exit 1
     fi  
     echo "exec $sm_name ..."
-    daemon=$(read_ini ${SM_DIR}/user/${sm_name}.service Service ExecStart) 
+    daemon=$(read_ini ${SM_DIR}/user/${sm_short_name}.service Service ExecStart) 
     echo $daemon
     $daemon
     ;;
   # two command to create or remove symbol link from user directory to work directory
   e|enable)
-    if [ -f ${SM_DIR}/user/${sm_name}.service ]; then
-      ln -sf ${SM_DIR}/user/${sm_name}.service ${SM_DIR}/work/${sm_name}.service
+    if [[ -n "${sm_dir}" && ! -d ${SM_DIR}/work/${sm_dir} ]]; then
+      mkdir -p ${SM_DIR}/work/${sm_dir}
+      mkdir -p ${SM_DIR}/pid/${sm_dir}
+      mkdir -p ${SM_DIR}/log/${sm_dir}
+    fi
+    if [ -f ${SM_DIR}/user/${sm_short_name}.service ]; then
+      ln -sf ${SM_DIR}/user/${sm_short_name}.service ${SM_DIR}/work/${sm_name}.service
     else
       echo "warning, ${sm_name} not found."
       exit 1
@@ -113,32 +125,62 @@ case $sm_cmd in
     fi
     ;;    
   # two all commands, batch do something
-  run-all)
-    applist=$(ls ${SM_DIR}/work/)
-    for app in $applist
-    do
-      name=${app%%.*}
-      if [ "${name}" = "sm-monitor" ]; then
-        echo $name > /dev/null
-      else
-        sm start $name
-      fi
-    done
+  run-all|start-all)
+    if [[ "x${sm_name}" = "x" || "x${sm_name}" = "x${IGNORE_SUBDIR}" ]]; then
+      applist=$(ls ${SM_DIR}/work/)
+      for app in $applist
+      do
+        name=${app%%.*}
+        if [ -d ${SM_DIR}/work/${name} ]; then
+          if [ ! "x${sm_name}" = "x${IGNORE_SUBDIR}" ]; then
+            sm run-all $name
+          fi
+        else
+          sm run $name
+        fi
+      done
+      exit 0
+    fi
+    if [[ -n "${sm_name}" && -d ${SM_DIR}/work/${sm_name}  ]]; then # sm_name is dir name
+      subapplist=$(ls ${SM_DIR}/work/${sm_name})
+      for sub in $subapplist
+      do
+        subname=${sub%%.*}
+        sm run ${sm_name}/${subname}
+      done
+      exit 0
+    fi
     ;;
-  kill-all)
-    applist=$(ls ${SM_DIR}/work/)
-    for app in $applist
-    do
-      name=${app%%.*}
-      if [ "${name}" = "sm-monitor" ]; then
-        echo $name > /dev/null
-      else
-        sm stop $name
-      fi
-    done
+  kill-all|stop-all)
+    if [[ "x${sm_name}" = "x" || "x${sm_name}" = "x${IGNORE_SUBDIR}" ]]; then
+      applist=$(ls ${SM_DIR}/work/)
+      for app in $applist
+      do
+        name=${app%%.*}
+        if [ -d ${SM_DIR}/work/${name} ]; then
+          if [ ! "x${sm_name}" = "x${IGNORE_SUBDIR}" ]; then
+            sm kill-all $name
+          fi
+        else
+          if [ ! "${name}" = "sm-monitor" ]; then
+            sm kill $name
+          fi
+        fi
+      done
+      exit 0
+    fi
+    if [[ -n "${sm_name}" && -d ${SM_DIR}/work/${sm_name}  ]]; then # sm_name is dir name
+      subapplist=$(ls ${SM_DIR}/work/${sm_name})
+      for sub in $subapplist
+      do
+        subname=${sub%%.*}
+        sm kill ${sm_name}/${subname}
+      done
+      exit 0
+    fi
     ;;
   r|run|start)
-    if [ "x${sm_name}" == "x" ]; then
+    if [ "x${sm_name}" = "x" ]; then
       usage
       exit 1
     fi
@@ -201,7 +243,7 @@ case $sm_cmd in
     done    
     ;;     
   k|kill|stop)
-    if [ "x${sm_name}" == "x" ]; then
+    if [ "x${sm_name}" = "x" ]; then
       usage
       exit 1
     fi
@@ -221,48 +263,59 @@ case $sm_cmd in
       exit 4
     fi
     ;;
-  s)
-    if [ "x${sm_name}" == "x" ]; then
+  s|status)
+    if [ "x${sm_name}" = "x" ]; then
       applist=$(ls ${SM_DIR}/work/)
       for app in $applist
       do
         name=${app%%.*}
-        sm s $name
+        sm ${sm_cmd} ${name}
       done
       exit 0
     fi
-    last_pid=`test -f ${SM_DIR}/pid/${sm_name}.pid && cat ${SM_DIR}/pid/${sm_name}.pid` || last_pid=-1
-    ps -p $last_pid > /dev/null 2>&1
-    status=$?
-    if [ $status -eq 0 ]; then
-      $ECHO "\033[32m active (running) \033[0m [$sm_name] -- $last_pid"
-    else
-      $ECHO "\033[31m inactive \033[0m [$sm_name]"
-    fi
-    ;;
-  status)
-    if [ "x${sm_name}" == "x" ]; then
+    if [ "x${sm_name}" = "x${IGNORE_SUBDIR}" ]; then
       applist=$(ls ${SM_DIR}/work/)
       for app in $applist
       do
         name=${app%%.*}
-        sm status $name
+        if [ ! -d ${SM_DIR}/work/${name} ]; then # skip sub dir
+          sm ${sm_cmd} ${name}
+        fi
       done
       exit 0
+    fi    
+    if [ -d ${SM_DIR}/work/${sm_name} ]; then
+      subapplist=$(ls ${SM_DIR}/work/${sm_name}/)
+      for sub in $subapplist
+      do
+        sub_name=${sub%%.*}
+        sm ${sm_cmd} ${sm_name}/$sub_name
+      done
+      exit 0
+    fi
+    if [ ! -f ${SM_DIR}/work/${sm_name}.service ]; then
+      echo "${sm_name} not found." 
+      exit 9
     fi
     last_pid=`test -f ${SM_DIR}/pid/${sm_name}.pid && cat ${SM_DIR}/pid/${sm_name}.pid` || last_pid=-1
     ps -p $last_pid > /dev/null 2>&1
     status=$?
+    cmd_line=""
     if [ $status -eq 0 ]; then
-      line=`ps -f -p $last_pid | tail -n 1`
-      $ECHO "\033[32m active (running) \033[0m [$sm_name] -- $last_pid /${line#*/}"
+      if [ ${sm_cmd} = "status" ]; then
+        line=`ps -f -p $last_pid | tail -n 1`
+        cmd_line="/${line#*/}"
+      fi
+      $ECHO "\033[32m active (running) \033[0m [$sm_name] -- $last_pid ${cmd_line}"
     else
-      daemon=$(read_ini ${SM_DIR}/work/${sm_name}.service Service ExecStart)
-      $ECHO "\033[31m inactive \033[0m [$sm_name]  --  $daemon"
+      if [ ${sm_cmd} = "status" ]; then
+        cmd_line="-- $(read_ini ${SM_DIR}/work/${sm_name}.service Service ExecStart)"
+      fi
+      $ECHO "\033[31m inactive \033[0m [$sm_name] ${cmd_line}"
     fi
     ;;
   log)
-    if [ "x${sm_name}" == "x" ]; then
+    if [ "x${sm_name}" = "x" ]; then
       usage
       exit 1
     fi
